-- V1145: 补全 alert_rules.type 枚举值，同步 Java AlertType 新增项
-- CO-523 #1/1 到期提醒 — PERFORMANCE_EXPIRY/CA_EXPIRY/CA_BORROW_OVERDUE 三个枚举值在数据库缺失，导致到期提醒静默失败
ALTER TABLE alert_rules
    MODIFY COLUMN type enum('DEADLINE','BUDGET','RISK','DOCUMENT','QUALIFICATION_EXPIRY','DEPOSIT_RETURN','PERFORMANCE_EXPIRY','CA_EXPIRY','CA_BORROW_OVERDUE') NOT NULL;
